version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: rating-system-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d leverx_project"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: rating-system-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  app:
    build: .
    container_name: rating-system-app
    ports:
      - "8080:8080"
    environment:
      redis-host: ${REDIS_HOST}
      redis-port: ${REDIS_PORT}
      rating-system.key: ${RATING_SYSTEM_KEY}
      email: ${MAIL}
      emailp: ${MAILP}

      JAVA_TOOL_OPTIONS: >-
        -Djdbc.url=${JDBC_URL}
        -Djdbc.username=${POSTGRES_USER}
        -Djdbc.password=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata:
  redisdata: